from_latest_tag = true
tag_prefix = "v"
branch_whitelist = ["main"]
skip_untracked = false
disable_changelog = false

pre_bump_hooks = []

post_bump_hooks = [
    "git push",
    "git push origin {{version_tag}}",
]

[changelog]
path = "CHANGELOG.md"
template = "remote"
remote = "github.com"
owner = "Rubio-Enterprises"
repository = "marvin-time-tracker"

[commit_types]
chore = { omit_from_changelog = true }
